language: node_js

node_js:
  - "8.9"

notifications:
  email: false

cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $travis
  on:
    branch: master
